fieldLayouts:
  44555cf4-e276-4fba-9181-8a27159d997b:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\assets\AssetTitleField
            warning: null
            width: 100
        name: Contenido
        sortOrder: 1
fs: tuMoto
handle: tuMoto
hasUrls: true
name: 'Tu Moto'
sortOrder: 1
titleTranslationKeyFormat: null
titleTranslationMethod: site
url: '@web/tumoto'
