columnSuffix: null
contentColumnType: text
fieldGroup: c0643579-92bd-49b2-b204-2e8083ea32cf # Menu Digital
handle: grams
instructions: ''
name: 'Porción en gramos/Mililitros'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: ''
  columnType: null
  initialRows: '4'
  multiline: ''
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
