columnSuffix: nkabehvo
contentColumnType: string(7)
fieldGroup: 7cab7bc5-2156-4ed0-87d3-49745370d305 # VARIABLES DEMO
handle: secondaryColor
instructions: ''
name: 'Color Secundario'
searchable: false
settings:
  defaultColor: '#f2f0e6'
translationKeyFormat: null
translationMethod: none
type: craft\fields\Color
