dateModified: 1718393075
email:
  fromEmail: alarrynk@gmail.com
  fromName: Ubox
  transportType: craft\mail\transportadapters\Sendmail
meta:
  __names__:
    0a94cfd3-d7fd-4725-992f-3bb365a17c81: 'Color Secundario' # Color Secundario
    1b7ca71f-64c7-4699-9fd5-536310527b30: 'Color primario (Valores RGB sin Alpha)' # Color primario (Valores RGB sin Alpha)
    01ef143d-bf3d-4319-9b04-1b2e23681839: 'Porción en gramos/Mililitros' # Porción en gramos/Mililitros
    02b99efe-7f35-4022-a9ee-59d0c0948ce3: Precio # Precio
    3ac43b9a-6a84-48c9-bf94-ad3912bcdb50: 'Menú Digital' # Menú Digital
    3d8620da-89ed-41c0-bd97-6a2934885bcf: Acento # Acento
    7c8c0732-67c6-476e-858e-9b9ec5780109: Ubox # Ubox
    7cab7bc5-2156-4ed0-87d3-49745370d305: 'VARIABLES DEMO' # VARIABLES DEMO
    8e68b477-d2e8-4c91-bb76-952d4d2c0468: Menus # Menus
    38f649eb-6dc0-4c90-9581-6863d4f6c923: Logo # Logo
    97ea7db2-8920-453c-9905-639afe4230d9: Menus # Menus
    198c99ea-5ccd-41bf-a65b-025832c82192: 'Descripción del platillo' # Descripción del platillo
    227b408b-3df1-4aac-91b6-1929cd1ead1d: Menus # Menus
    962b0bef-0527-4e56-a819-33cfa3f0fff5: 'Menú Digital Demo' # Menú Digital Demo
    06877d42-d677-4ef1-a092-2c297d188b51: Ubox # Ubox
    30901ff3-1441-482e-be94-ccbe056730f4: 'Tu Moto' # Tu Moto
    41495cc6-b3a4-4a8e-962f-375d832baf20: menus # menus
    3670293b-cce1-4c94-8d0e-f818616a0646: Menu # Menu
    5152587a-75e7-4924-8c37-01e668f3f8e1: 'Platillos relacionados' # Platillos relacionados
    7812174d-b068-477c-899f-45a4b04c63f5: 'Meal Thumbnail' # Meal Thumbnail
    58728069-2060-41b6-ae2f-996d1a6ade0a: 'Categoria del platillo' # Categoria del platillo
    a64b0bd5-eecd-46e3-b4ba-e028137232fb: 'Menú Demo Digital ' # Menú Demo Digital 
    a2797350-b45a-436f-b536-a29455bc2fce: 'Categoría del Platillo' # Categoría del Platillo
    c0643579-92bd-49b2-b204-2e8083ea32cf: 'Menu Digital' # Menu Digital
    c3e48889-6808-4431-848b-b9572942d24e: Imagen # Imagen
    d48dfd4b-b4d4-478f-9199-c50d5a3e9efc: 'Menú Digital Demo' # Menú Digital Demo
    d828c040-fb7e-42ea-9a84-6227909b1830: Common # Common
    d8919276-61ac-412a-871d-286378e6fdc3: QR # QR
    e97dc74c-f1e6-40d2-b435-d5ca8494154c: 'Category Thumbnail' # Category Thumbnail
plugins:
  feed-me:
    edition: standard
    enabled: true
    schemaVersion: 4.4.1
  qrcode:
    edition: standard
    enabled: true
    schemaVersion: 0.0.1
  splash:
    edition: standard
    enabled: true
    schemaVersion: 3.0.0
    settings:
      authorField: ''
      authorUrlField: ''
      colorField: ''
      volume: '3'
system:
  edition: solo
  live: true
  name: Ubox
  schemaVersion: 3.8.0.1
  timeZone: America/Los_Angeles
users:
  allowPublicRegistration: false
  defaultGroup: null
  photoSubpath: null
  photoVolumeUid: null
  requireEmailVerification: true
